export class Country {
    id: string;
    name: string;
    countryCode: string;
    isEnabled: string;
}

export const CountryData: Country[] = [
{id: 'CHN', name: 'CHINA', countryCode: '156', isEnabled: 'Y'}					,
{id: 'JPN', name: 'JAPAN', countryCode: '392', isEnabled: 'Y'}                      ,
{id: 'KOR', name: 'KOREA(SOUTH)', countryCode: '410', isEnabled: 'Y'}               ,
{id: 'THA', name: 'THAILAND', countryCode: '764', isEnabled: 'Y'}                   ,
{id: 'USA', name: 'UNITED STATES OF AMERICA', countryCode: '840', isEnabled: 'Y'}   ,
{id: '', name: '', countryCode: '', isEnabled: ''}                                  ,
{id: 'ALB', name: 'ALBANIA', countryCode: '008', isEnabled: 'Y'}                    ,
{id: 'DZA', name: 'ALGERIA', countryCode: '012', isEnabled: 'Y'}                    ,
{id: 'ASM', name: 'AMERICAN SAMOA', countryCode: '016', isEnabled: 'Y'}             ,
{id: 'ASM', name: 'AMERICAN SAMOA', countryCode: '017', isEnabled: 'Y'}             ,
{id: 'AND', name: 'ANDORRA', countryCode: '020', isEnabled: 'Y'}                    ,
{id: 'AGO', name: 'ANGOLA', countryCode: '024', isEnabled: 'Y'}                     ,
{id: 'AIA', name: 'ANGUILLA', countryCode: '660', isEnabled: 'Y'}                   ,
{id: 'ATG', name: 'ANTIGUA AND BARBUDA', countryCode: '028', isEnabled: 'Y'}        ,
{id: 'ARG', name: 'ARGENTINA', countryCode: '032', isEnabled: 'Y'}                  ,
{id: 'ARM', name: 'ARMENIA', countryCode: '051', isEnabled: 'Y'}                    ,
{id: 'ABW', name: 'ARUBA', countryCode: '533', isEnabled: 'Y'}                      ,
{id: 'AUS', name: 'AUSTRALIA', countryCode: '036', isEnabled: 'Y'}                  ,
{id: 'AUT', name: 'AUSTRIA', countryCode: '040', isEnabled: 'Y'}                    ,
{id: 'AZE', name: 'AZERBAIJAN', countryCode: '031', isEnabled: 'Y'}                 ,
{id: 'BHS', name: 'BAHAMAS', countryCode: '044', isEnabled: 'Y'}                    ,
{id: 'BHR', name: 'BAHRAIN', countryCode: '048', isEnabled: 'Y'}                    ,
{id: 'BGD', name: 'BANGLADESH', countryCode: '050', isEnabled: 'Y'}                 ,
{id: 'BRB', name: 'BARBADOS', countryCode: '052', isEnabled: 'Y'}                   ,
{id: 'BLR', name: 'BELARUS', countryCode: '112', isEnabled: 'Y'}                    ,
{id: 'BEL', name: 'BELGIUM', countryCode: '056', isEnabled: 'Y'}                    ,
{id: 'BLZ', name: 'BELIZE', countryCode: '084', isEnabled: 'Y'}                     ,
{id: 'BEN', name: 'BENIN', countryCode: '204', isEnabled: 'Y'}                      ,
{id: 'BMU', name: 'BERMUDA', countryCode: '060', isEnabled: 'Y'}                    ,
{id: 'BTN', name: 'BHUTAN', countryCode: '064', isEnabled: 'Y'}                     ,
{id: 'BOL', name: 'BOLIVIA', countryCode: '068', isEnabled: 'Y'}                    ,
{id: 'BIH', name: 'BOSNIA AND HERZEGOVINA', countryCode: '070', isEnabled: 'Y'}     ,
{id: 'BWA', name: 'BOTSWANA', countryCode: '072', isEnabled: 'Y'}                   ,
{id: 'BRA', name: 'BRAZIL', countryCode: '076', isEnabled: 'Y'}                     ,
{id: 'VGB', name: 'BRITISH VIRGIN ISLANDS', countryCode: '092', isEnabled: 'Y'}     ,
{id: 'BRN', name: 'BRUNEI DARUSSALAM', countryCode: '096', isEnabled: 'Y'}          ,
{id: 'BGR', name: 'BULGARIA', countryCode: '100', isEnabled: 'Y'}                   ,
{id: 'BFA', name: 'BURKINA FASO', countryCode: '854', isEnabled: 'Y'}               ,
{id: 'BDI', name: 'BURUNDI', countryCode: '108', isEnabled: 'Y'}                    ,
{id: 'KHM', name: 'CAMBODIA', countryCode: '116', isEnabled: 'Y'}                   ,
{id: 'CMR', name: 'CAMEROON', countryCode: '120', isEnabled: 'Y'}                   ,
{id: 'CAN', name: 'CANADA', countryCode: '124', isEnabled: 'Y'}                     ,
{id: 'CPV', name: 'CAPE VERDE', countryCode: '132', isEnabled: 'Y'}                 ,
{id: 'CYM', name: 'CAYMAN ISLANDS', countryCode: '136', isEnabled: 'Y'}             ,
{id: 'CAF', name: 'CENTRAL AFRICAN REPUBLIC', countryCode: '140', isEnabled: 'Y'}   ,
{id: 'TCD', name: 'CHAD', countryCode: '148', isEnabled: 'Y'}                       ,
{id: 'CHL', name: 'CHILE', countryCode: '152', isEnabled: 'Y'}                      ,
{id: 'COL', name: 'COLOMBIA', countryCode: '170', isEnabled: 'Y'}                   ,
{id: 'COM', name: 'COMOROS', countryCode: '174', isEnabled: 'Y'}                    ,
{id: 'COG', name: 'CONGO(BRAZZAVILLE)', countryCode: '178', isEnabled: 'Y'}         ,
{id: 'COK', name: 'COOK ISLANDS', countryCode: '184', isEnabled: 'Y'}               ,
{id: 'CRI', name: 'COSTA RICA', countryCode: '188', isEnabled: 'Y'}                 ,
{id: 'HRV', name: 'CROATIA', countryCode: '191', isEnabled: 'Y'}                    ,
{id: 'CYP', name: 'CYPRUS', countryCode: '196', isEnabled: 'Y'}                     ,
{id: 'CZE', name: 'CZECH REPUBLIC', countryCode: '203', isEnabled: 'Y'}             ,
{id: 'CIV', name: 'CoTE D\'IVOIRE', countryCode: '384', isEnabled: 'Y'}              ,
{id: 'DNK', name: 'DENMARK', countryCode: '208', isEnabled: 'Y'}                    ,
{id: 'DJI', name: 'DJIBOUTI', countryCode: '262', isEnabled: 'Y'}                   ,
{id: 'DMA', name: 'DOMINICA', countryCode: '212', isEnabled: 'Y'}                   ,
{id: 'DOM', name: 'DOMINICAN REPUBLIC', countryCode: '214', isEnabled: 'Y'}         ,
{id: 'ECU', name: 'ECUADOR', countryCode: '218', isEnabled: 'Y'}                    ,
{id: 'EGY', name: 'EGYPT', countryCode: '818', isEnabled: 'Y'}                      ,
{id: 'SLV', name: 'EL SALVADOR', countryCode: '222', isEnabled: 'Y'}                ,
{id: 'GNQ', name: 'EQUATORIAL GUINEA', countryCode: '226', isEnabled: 'Y'}          ,
{id: 'ERI', name: 'ERITREA', countryCode: '232', isEnabled: 'Y'}                    ,
{id: 'EST', name: 'ESTONIA', countryCode: '233', isEnabled: 'Y'}                    ,
{id: 'ETH', name: 'ETHIOPIA', countryCode: '231', isEnabled: 'Y'}                   ,
{id: 'FLK', name: 'FALKLAND ISLANDS (MALVINAS)', countryCode: '238', isEnabled: 'Y'},
{id: 'FRO', name: 'FAROE ISLANDS', countryCode: '234', isEnabled: 'Y'}              ,
{id: 'FJI', name: 'FIJI', countryCode: '242', isEnabled: 'Y'}                       ,
{id: 'FIN', name: 'FINLAND', countryCode: '246', isEnabled: 'Y'}                    ,
{id: 'FRA', name: 'FRANCE', countryCode: '250', isEnabled: 'Y'}                     ,
{id: 'GUF', name: 'FRENCH GUIANA', countryCode: '254', isEnabled: 'Y'}              ,
{id: 'PYF', name: 'FRENCH POLYNESIA', countryCode: '258', isEnabled: 'Y'}           ,
{id: 'GAB', name: 'GABON', countryCode: '266', isEnabled: 'Y'}                      ,
{id: 'GMB', name: 'GAMBIA', countryCode: '270', isEnabled: 'Y'}                     ,
{id: 'GEO', name: 'GEORGIA', countryCode: '268', isEnabled: 'Y'}                    ,
{id: 'DEU', name: 'GERMANY', countryCode: '276', isEnabled: 'Y'}                    ,
{id: 'GHA', name: 'GHANA', countryCode: '288', isEnabled: 'Y'}                      ,
{id: 'GIB', name: 'GIBRALTAR', countryCode: '292', isEnabled: 'Y'}                  ,
{id: 'GRC', name: 'GREECE', countryCode: '300', isEnabled: 'Y'}                     ,
{id: 'GRL', name: 'GREENLAND', countryCode: '304', isEnabled: 'Y'}                  ,
{id: 'GRD', name: 'GRENADA', countryCode: '308', isEnabled: 'Y'}                    ,
{id: 'GLP', name: 'GUADELOUPE', countryCode: '312', isEnabled: 'Y'}                 ,
{id: 'GUM', name: 'GUAM', countryCode: '316', isEnabled: 'Y'}                       ,
{id: 'GTM', name: 'GUATEMALA', countryCode: '320', isEnabled: 'Y'}                  ,
{id: 'GGY', name: 'GUERNSEY', countryCode: '831', isEnabled: 'Y'}                   ,
{id: 'GIN', name: 'GUINEA', countryCode: '324', isEnabled: 'Y'}                     ,
{id: 'GNB', name: 'GUINEA-BISSAU', countryCode: '624', isEnabled: 'Y'}              ,
{id: 'GUY', name: 'GUYANA', countryCode: '328', isEnabled: 'Y'}                     ,
{id: 'HTI', name: 'HAITI', countryCode: '332', isEnabled: 'Y'}                      ,
{id: 'VAT', name: 'HOLY SEE(VATICAN CITY STATE)', countryCode: '336', isEnabled: 'Y'},
{id: 'HND', name: 'HONDURAS', countryCode: '340', isEnabled: 'Y'}                   ,
{id: 'HKG', name: 'HONG KONG, SAR CHINA', countryCode: '344', isEnabled: 'Y'}       ,
{id: 'HUN', name: 'HUNGARY', countryCode: '348', isEnabled: 'Y'}                    ,
{id: 'ISL', name: 'ICELAND', countryCode: '352', isEnabled: 'Y'}                    ,
{id: 'IND', name: 'INDIA', countryCode: '356', isEnabled: 'Y'}                      ,
{id: 'IDN', name: 'INDONESIA', countryCode: '360', isEnabled: 'Y'}                  ,
{id: 'IRL', name: 'IRELAND', countryCode: '372', isEnabled: 'Y'}                    ,
{id: 'IMN', name: 'ISLE OF MAN', countryCode: '833', isEnabled: 'Y'}                ,
 {id: 'ISR', name: 'ISRAEL', countryCode: '376', isEnabled: 'Y'}                    ,
 {id: 'ITA', name: 'ITALY', countryCode: '380', isEnabled: 'Y'}                     ,
 {id: 'JAM', name: 'JAMAICA', countryCode: '388', isEnabled: 'Y'}                   ,
 {id: 'JEY', name: 'JERSEY', countryCode: '832', isEnabled: 'Y'}                    ,
 {id: 'JOR', name: 'JORDAN', countryCode: '400', isEnabled: 'Y'}                    ,
 {id: 'KAZ', name: 'KAZAKHSTAN', countryCode: '398', isEnabled: 'Y'}                ,
 {id: 'KEN', name: 'KENYA', countryCode: '404', isEnabled: 'Y'}                     ,
 {id: 'KIR', name: 'KIRIBATI', countryCode: '296', isEnabled: 'Y'}                  ,
 {id: 'KWT', name: 'KUWAIT', countryCode: '414', isEnabled: 'Y'}                    ,
 {id: 'KGZ', name: 'KYRGYZSTAN', countryCode: '417', isEnabled: 'Y'}                ,
 {id: 'LAO', name: 'LAO PDR', countryCode: '418', isEnabled: 'Y'}                   ,
 {id: 'LVA', name: 'LATVIA', countryCode: '428', isEnabled: 'Y'}                    ,
 {id: 'LSO', name: 'LESOTHO', countryCode: '426', isEnabled: 'Y'}                   ,
 {id: 'LBR', name: 'LIBERIA', countryCode: '430', isEnabled: 'Y'}                   ,
 {id: 'LIE', name: 'LIECHTENSTEIN', countryCode: '438', isEnabled: 'Y'}             ,
 {id: 'LTU', name: 'LITHUANIA', countryCode: '440', isEnabled: 'Y'}                 ,
 {id: 'LUX', name: 'LUXEMBOURG', countryCode: '442', isEnabled: 'Y'}                ,
 {id: 'MAC', name: 'MACAO, SAR CHINA', countryCode: '446', isEnabled: 'Y'}          ,
 {id: 'MKD', name: 'MACEDONIA, REPUBLIC OF', countryCode: '807', isEnabled: 'Y'}    ,
 {id: 'MDG', name: 'MADAGASCAR', countryCode: '450', isEnabled: 'Y'}                ,
 {id: 'MWI', name: 'MALAWI', countryCode: '454', isEnabled: 'Y'}                    ,
 {id: 'MYS', name: 'MALAYSIA', countryCode: '458', isEnabled: 'Y'}                  ,
 {id: 'MDV', name: 'MALDIVES', countryCode: '462', isEnabled: 'Y'}                  ,
 {id: 'MLI', name: 'MALI', countryCode: '466', isEnabled: 'Y'}                      ,
 {id: 'MLT', name: 'MALTA', countryCode: '470', isEnabled: 'Y'}                     ,
 {id: 'MHL', name: 'MARSHALL ISLANDS', countryCode: '584', isEnabled: 'Y'}          ,
 {id: 'MTQ', name: 'MARTINIQUE', countryCode: '474', isEnabled: 'Y'}                ,
 {id: 'MRT', name: 'MAURITANIA', countryCode: '478', isEnabled: 'Y'}                ,
 {id: 'MUS', name: 'MAURITIUS', countryCode: '480', isEnabled: 'Y'}                 ,
 {id: 'MYT', name: 'MAYOTTE', countryCode: '175', isEnabled: 'Y'}                   ,
 {id: 'MEX', name: 'MEXICO', countryCode: '484', isEnabled: 'Y'}                    ,
 {id: 'FSM', name: 'MICRONESIA, FEDERATED STATES OF', countryCode: '583', isEnabled: 'Y'},
 {id: 'MDA', name: 'MOLDOVA', countryCode: '498', isEnabled: 'Y'}                   ,
 {id: 'MCO', name: 'MONACO', countryCode: '492', isEnabled: 'Y'}                    ,
 {id: 'MNG', name: 'MONGOLIA', countryCode: '496', isEnabled: 'Y'}                  ,
 {id: 'MNE', name: 'MONTENEGRO', countryCode: '499', isEnabled: 'Y'}                ,
 {id: 'MSR', name: 'MONTSERRAT', countryCode: '500', isEnabled: 'Y'}                ,
 {id: 'MAR', name: 'MOROCCO', countryCode: '504', isEnabled: 'Y'}                   ,
 {id: 'MOZ', name: 'MOZAMBIQUE', countryCode: '508', isEnabled: 'Y'}                ,
 {id: 'MMR', name: 'MYANMAR', countryCode: '104', isEnabled: 'Y'}                   ,
 {id: 'NAM', name: 'NAMIBIA', countryCode: '516', isEnabled: 'Y'}                   ,
 {id: 'NRU', name: 'NAURU', countryCode: '520', isEnabled: 'Y'}                     ,
 {id: 'NPL', name: 'NEPAL', countryCode: '524', isEnabled: 'Y'}                     ,
 {id: 'NLD', name: 'NETHERLANDS', countryCode: '528', isEnabled: 'Y'}               ,
 {id: 'ANT', name: 'NETHERLANDS ANTILLES', countryCode: '530', isEnabled: 'Y'}      ,
 {id: 'NCL', name: 'NEW CALEDONIA', countryCode: '540', isEnabled: 'Y'}             ,
 {id: 'NZL', name: 'NEW ZEALAND', countryCode: '554', isEnabled: 'Y'}               ,
 {id: 'NIC', name: 'NICARAGUA', countryCode: '558', isEnabled: 'Y'}                 ,
 {id: 'NER', name: 'NIGER', countryCode: '562', isEnabled: 'Y'}                     ,
 {id: 'NGA', name: 'NIGERIA', countryCode: '566', isEnabled: 'Y'}                   ,
 {id: 'NIU', name: 'NIUE', countryCode: '570', isEnabled: 'Y'}                      ,
 {id: 'MNP', name: 'NORTHERN MARIANA ISLANDS', countryCode: '580', isEnabled: 'Y'}  ,
 {id: 'NOR', name: 'NORWAY', countryCode: '578', isEnabled: 'Y'}                    ,
 {id: 'OMN', name: 'OMAN', countryCode: '512', isEnabled: 'Y'}                      ,
 {id: 'PAK', name: 'PAKISTAN', countryCode: '586', isEnabled: 'Y'}                  ,
 {id: 'PLW', name: 'PALAU', countryCode: '585', isEnabled: 'Y'}                     ,
 {id: 'PSE', name: 'PALESTINIAN TERRITORY', countryCode: '275', isEnabled: 'Y'}     ,
 {id: 'PAN', name: 'PANAMA', countryCode: '591', isEnabled: 'Y'}                    ,
 {id: 'PNG', name: 'PAPUA NEW GUINEA', countryCode: '598', isEnabled: 'Y'}          ,
 {id: 'PRY', name: 'PARAGUAY', countryCode: '600', isEnabled: 'Y'}                  ,
 {id: 'PER', name: 'PERU', countryCode: '604', isEnabled: 'Y'}                      ,
 {id: 'PHL', name: 'PHILIPPINES', countryCode: '608', isEnabled: 'Y'}               ,
 {id: 'POL', name: 'POLAND', countryCode: '616', isEnabled: 'Y'}                    ,
 {id: 'PRT', name: 'PORTUGAL', countryCode: '620', isEnabled: 'Y'}                  ,
 {id: 'PRI', name: 'PUERTO RICO', countryCode: '630', isEnabled: 'Y'}               ,
 {id: 'QAT', name: 'QATAR', countryCode: '634', isEnabled: 'Y'}                     ,
 {id: 'ROU', name: 'ROMANIA', countryCode: '642', isEnabled: 'Y'}                   ,
 {id: 'RWA', name: 'RWANDA', countryCode: '646', isEnabled: 'Y'}                    ,
 {id: 'REU', name: 'ReUNION', countryCode: '638', isEnabled: 'Y'}                   ,
 {id: 'KNA', name: 'SAINT KITTS AND NEVIS', countryCode: '659', isEnabled: 'Y'}     ,
 {id: 'LCA', name: 'SAINT LUCIA', countryCode: '662', isEnabled: 'Y'}               ,
 {id: 'SPM', name: 'SAINT PIERRE AND MIQUELON', countryCode: '666', isEnabled: 'Y'} ,
 {id: 'VCT', name: 'SAINT VINCENT AND GRENADINES', countryCode: '670', isEnabled: 'Y'},
 {id: 'WSM', name: 'SAMOA', countryCode: '882', isEnabled: 'Y'}                     ,
 {id: 'SMR', name: 'SAN MARINO', countryCode: '674', isEnabled: 'Y'}                ,
 {id: 'STP', name: 'SAO TOME AND PRINCIPE', countryCode: '678', isEnabled: 'Y'}     ,
 {id: 'SAU', name: 'SAUDI ARABIA', countryCode: '682', isEnabled: 'Y'}              ,
 {id: 'SEN', name: 'SENEGAL', countryCode: '686', isEnabled: 'Y'}                   ,
 {id: 'SRB', name: 'SERBIA', countryCode: '688', isEnabled: 'Y'}                    ,
 {id: 'SYC', name: 'SEYCHELLES', countryCode: '690', isEnabled: 'Y'}                ,
 {id: 'SLE', name: 'SIERRA LEONE', countryCode: '694', isEnabled: 'Y'}              ,
 {id: 'SGP', name: 'SINGAPORE', countryCode: '702', isEnabled: 'Y'}                 ,
 {id: 'SVK', name: 'SLOVAKIA', countryCode: '703', isEnabled: 'Y'}                  ,
 {id: 'SVN', name: 'SLOVENIA', countryCode: '705', isEnabled: 'Y'}                  ,
 {id: 'SLB', name: 'SOLOMON ISLANDS', countryCode: '090', isEnabled: 'Y'}           ,
 {id: 'ZAF', name: 'SOUTH AFRICA', countryCode: '710', isEnabled: 'Y'}              ,
 {id: 'SSD', name: 'SOUTH SUDAN', countryCode: '728', isEnabled: 'Y'}               ,
 {id: 'ESP', name: 'SPAIN', countryCode: '724', isEnabled: 'Y'}                     ,
 {id: 'LKA', name: 'SRI LANKA', countryCode: '144', isEnabled: 'Y'}                 ,
 {id: 'SUR', name: 'SURINAME', countryCode: '740', isEnabled: 'Y'}                  ,
 {id: 'SWZ', name: 'SWAZILAND', countryCode: '748', isEnabled: 'Y'}                 ,
 {id: 'SWE', name: 'SWEDEN', countryCode: '752', isEnabled: 'Y'}                    ,
 {id: 'CHE', name: 'SWITZERLAND', countryCode: '756', isEnabled: 'Y'}               ,
 {id: 'TWN', name: 'TAIWAN, REPUBLIC OF CHINA', countryCode: '158', isEnabled: 'Y'} ,
 {id: 'TJK', name: 'TAJIKISTAN', countryCode: '762', isEnabled: 'Y'}                ,
 {id: 'TZA', name: 'TANZANIA, UNITED REPUBLIC OF', countryCode: '834', isEnabled: 'Y'},
 {id: 'TLS', name: 'TIMOR-LESTE', countryCode: '626', isEnabled: 'Y'}               ,
 {id: 'TGO', name: 'TOGO', countryCode: '768', isEnabled: 'Y'}                      ,
 {id: 'TON', name: 'TONGA', countryCode: '776', isEnabled: 'Y'}                     ,
 {id: 'TTO', name: 'TRINIDAD AND TOBAGO', countryCode: '780', isEnabled: 'Y'}       ,
 {id: 'TUN', name: 'TUNISIA', countryCode: '788', isEnabled: 'Y'}                   ,
 {id: 'TUR', name: 'TURKEY', countryCode: '792', isEnabled: 'Y'}                    ,
 {id: 'TKM', name: 'TURKMENISTAN', countryCode: '795', isEnabled: 'Y'}              ,
 {id: 'TCA', name: 'TURKS AND CAICOS ISLANDS', countryCode: '796', isEnabled: 'Y'}  ,
 {id: 'TUV', name: 'TUVALU', countryCode: '798', isEnabled: 'Y'}                    ,
 {id: 'UGA', name: 'UGANDA', countryCode: '800', isEnabled: 'Y'}                    ,
 {id: 'ARE', name: 'UNITED ARAB EMIRATES', countryCode: '784', isEnabled: 'Y'}      ,
 {id: 'GBR', name: 'UNITED KINGDOM', countryCode: '826', isEnabled: 'Y'}            ,
 {id: 'URY', name: 'URUGUAY', countryCode: '858', isEnabled: 'Y'}                   ,
 {id: 'UZB', name: 'UZBEKISTAN', countryCode: '860', isEnabled: 'Y'}                ,
 {id: 'VUT', name: 'VANUATU', countryCode: '548', isEnabled: 'Y'}                   ,
 {id: 'VEN', name: 'VENEZUELA(BOLIVARIAN REPUBLIC)', countryCode: '862', isEnabled: 'Y'},
 {id: 'VNM', name: 'VIETNAM', countryCode: '704', isEnabled: 'Y'}                   ,
 {id: 'VIR', name: 'VIRGIN ISLANDS, US', countryCode: '850', isEnabled: 'Y'}        ,
 {id: 'WLF', name: 'WALLIS AND FUTUNA ISLANDS', countryCode: '876', isEnabled: 'Y'} ,
 {id: 'YEM', name: 'YEMEN', countryCode: '887', isEnabled: 'Y'}                     ,
 {id: 'ZMB', name: 'ZAMBIA', countryCode: '894', isEnabled: 'Y'}                    ,
 {id: 'ZWE', name: 'ZIMBABWE', countryCode: '716', isEnabled: 'Y'}
];
